export const links = [
  {
    url: "/transactions",
    label: "Transactions",
    icon: "FaReceipt",
    child: false,
    admin: false,
    parent: "",
  },
  {
    url: "/transactions/add",
    label: "Add a Transaction",
    icon: "FaPlus",
    child: true,
    admin: false,
    parent: "transactions",
  },
  {
    url: "/currencies",
    label: "Currencies",
    icon: "FaGear",
    child: true,
    admin: true,
    parent: "transactions",
  },
  {
    url: "/currencies/add",
    label: "Add Currency",
    icon: "FaPlus",
    child: true,
    admin: true,
    parent: "currencies",
  },
  {
    url: "/select-currencies",
    label: "Select currencies to use",
    icon: "FaGear",
    child: true,
    admin: false,
    parent: "transactions",
  },
  {
    url: "/payment-methods",
    label: "Payment Methods",
    icon: "FaGear",
    child: true,
    admin: false,
    parent: "transactions",
  },
  {
    url: "/payment-methods/add",
    label: "Add a payment method",
    child: true,
    admin: false,
    parent: "payment-methods",
  },
];
