export const links = [
  {
    url: "/transactions",
    label: "Transactions",
    icon: "FaReceipt",
    admin: false,
    hasChildren: true,
    parent: "",
  },
  {
    url: "/transactions/add",
    label: "Add a Transaction",
    icon: "FaPlus",
    child: true,
    admin: false,
    parent: "/transactions",
  },
  {
    url: "/currencies",
    label: "Currencies",
    icon: "FaGear",
    hasChildren: true,
    admin: false,
    parent: "",
  },
  {
    url: "/currencies/add",
    label: "Add Currency",
    icon: "FaPlus",
    child: true,
    admin: true,
    parent: "/currencies",
  },
  {
    url: "/transaction-categories",
    label: "Categories",
    hasChildren: true,
    child: false,
    admin: false,
    parent: "",
  },
  {
    url: "/transaction-categories/add",
    label: "Add transaction category",
    child: true,
    admin: false,
    parent: "/transaction-categories",
  },
  {
    url: "/payment-methods",
    label: "Payment Methods",
    icon: "FaGear",
    hasChildren: true,
    child: false,
    admin: false,
    parent: "",
  },
  {
    url: "/payment-methods/add",
    label: "Add a payment method",
    child: true,
    admin: false,
    parent: "/payment-methods",
  },
];
